# Import Library

In [2]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [6]:
from google.colab import files
upload = files.upload()

Saving covid_dataset (1).csv to covid_dataset (1).csv

In [7]:
df = pd.read_csv('covid_dataset (1).csv')

In [11]:
df

     age  gender  fever cough         city has_covid
0     26  Female   98.4   Wet      Houston       Yes
1     56  Female   99.0   Dry      Phoenix       Yes
2     73  Female  100.6   Dry  Los Angeles        No
3     81    Male  102.8   Dry     New York        No
4     52  Female   99.6   Dry     New York        No
..   ...     ...    ...   ...          ...       ...
195   18  Female  100.6   Wet      Chicago        No
196   51  Female  100.0   Wet      Phoenix        No
197   91    Male   98.9   Dry      Houston       Yes
198   75  Female  103.6   Dry  Los Angeles        No
199   41    Male  101.5   NaN      Phoenix        No

[200 rows x 6 columns]

In [13]:
df['city'].value_counts()

city
Houston        42
Los Angeles    42
Phoenix        40
New York       38
Chicago        38
Name: count, dtype: int64

In [24]:
df = df.dropna(subset=['cough'])

In [27]:
df['cough'].value_counts()

cough
Wet    76
Dry    63
Name: count, dtype: int64

In [28]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [ ]:
df = df.dropna(subset=['cough'])

# Train test split

In [29]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [31]:
X_train

     age  gender  fever cough         city
26    92  Female  103.6   Dry      Phoenix
7     75  Female   97.2   Wet     New York
176    6    Male   99.4   Wet      Phoenix
47    43    Male  100.0   Wet      Houston
56    56    Male   98.1   Dry      Phoenix
..   ...     ...    ...   ...          ...
132   95  Female   97.5   Wet      Phoenix
106   15    Male  100.8   Wet      Chicago
189   18   Other  101.3   Wet      Chicago
83    91   Other   98.8   Dry     New York
23    45  Female   98.6   Dry  Los Angeles

[111 rows x 5 columns]

# **Aam Zindagi**

In [32]:
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

X_test_fever = si.fit_transform(X_test[['fever']])

X_test_fever

array([[ 97.4],
       [ 97.6],
       [102.7],
       [ 99.1],
       [102.8],
       [100. ],
       [102.9],
       [101.5],
       [ 99.2],
       [101.1],
       [100.7],
       [101.4],
       [102.6],
       [ 99.3],
       [102.3],
       [101.9],
       [101. ],
       [103.6],
       [103. ],
       [102.4],
       [101.3],
       [ 99. ],
       [101.2],
       [ 98.9],
       [103.2],
       [ 98.8],
       [ 98.5],
       [100.6]])

In [33]:
df['cough'].value_counts()

cough
Wet    76
Dry    63
Name: count, dtype: int64

In [34]:
oe = OrdinalEncoder(categories=[['Wet','Dry']])
X_train_cough = oe.fit_transform(X_train[['cough']])

X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough

array([[1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.]])

In [38]:
ohe = OneHotEncoder(drop='first')
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']]).toarray()

X_test_gender_city = ohe.transform(X_test[['gender','city']]).toarray()

X_train_gender_city

array([[0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [44]:
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values
X_train_age

array([[ 92],
       [ 75],
       [  6],
       [ 43],
       [ 56],
       [ 91],
       [ 44],
       [ 33],
       [ 83],
       [ 68],
       [  9],
       [ 21],
       [ 31],
       [ 79],
       [ 93],
       [100],
       [ 73],
       [ 85],
       [ 84],
       [ 75],
       [ 25],
       [  4],
       [ 26],
       [ 26],
       [ 18],
       [  3],
       [ 58],
       [ 55],
       [ 99],
       [ 22],
       [ 26],
       [ 41],
       [ 17],
       [ 37],
       [ 77],
       [ 13],
       [ 91],
       [ 46],
       [ 95],
       [ 33],
       [ 75],
       [ 52],
       [ 94],
       [ 32],
       [ 54],
       [ 48],
       [ 18],
       [ 60],
       [ 18],
       [ 75],
       [ 59],
       [ 22],
       [ 26],
       [  8],
       [ 64],
       [ 52],
       [ 22],
       [ 89],
       [ 10],
       [ 44],
       [ 24],
       [ 45],
       [ 61],
       [ 73],
       [ 71],
       [  6],
       [ 43],
       [ 76],
       [ 35],
       [ 28],
       [100],
       [ 32],
       [ 66],
       [ 16],
       [ 17],
       [ 20],
       [ 16],
       [ 38],
       [ 26],
       [ 63],
       [ 34],
       [ 87],
       [ 42],
       [ 75],
       [ 62],
       [ 51],
       [ 62],
       [ 77],
       [ 15],
       [ 95],
       [ 21],
       [ 40],
       [ 42],
       [ 66],
       [ 82],
       [  5],
       [ 27],
       [ 52],
       [  7],
       [ 35],
       [ 15],
       [ 86],
       [ 51],
       [ 86],
       [ 53],
       [ 32],
       [ 95],
       [ 15],
       [ 18],
       [ 91],
       [ 45]])

In [47]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_test_transformed.shape

(28, 9)

# **Mentos Zindagi**

In [48]:
from sklearn.compose import ColumnTransformer

In [52]:
transformer = ColumnTransformer(transformers=[
    ('tnf1' , SimpleImputer() , ['fever']),
    ('tnf2' , OrdinalEncoder(categories=[['Wet','Dry']]),['cough']),
    ('tnf3',OneHotEncoder(drop='first'),['gender','city'])
] , remainder = 'passthrough')

In [53]:
transformer.fit_transform(X_train).shape

(111, 9)

In [54]:
transformer.fit_transform(X_test).shape

(28, 9)