# Pivot Table

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
from google.colab import files

In [ ]:
upload = files.upload()

Saving expense_data.csv to expense_data.csv

In [ ]:
df = sns.load_dataset('tips')

In [ ]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df.sample(5)

     total_bill  tip     sex smoker   day    time  size
49        18.04  3.0    Male     No   Sun  Dinner     2
56        38.01  3.0    Male    Yes   Sat  Dinner     4
160       21.50  3.5    Male     No   Sun  Dinner     4
27        12.69  2.0    Male     No   Sat  Dinner     2
136       10.33  2.0  Female     No  Thur   Lunch     2

In [ ]:
df.groupby('sex')[['total_bill']].mean()

/tmp/ipython-input-2388094044.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('sex')[['total_bill']].mean()

        total_bill
sex
Male     20.744076
Female   18.056897

In [ ]:
df.groupby(['sex','smoker'])[['total_bill']].mean()

/tmp/ipython-input-1859643203.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['sex','smoker'])[['total_bill']].mean()

               total_bill
sex    smoker
Male   Yes      22.284500
       No       19.791237
Female Yes      17.977879
       No       18.105185

In [ ]:
df.groupby(['sex','smoker'])[['total_bill']].mean().unstack()

/tmp/ipython-input-884363850.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['sex','smoker'])[['total_bill']].mean().unstack()

       total_bill
smoker        Yes         No
sex
Male    22.284500  19.791237
Female  17.977879  18.105185

In [ ]:
df.pivot_table(index='sex',columns='smoker',values='total_bill')

/tmp/ipython-input-1243499625.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex',columns='smoker',values='total_bill')

smoker        Yes         No
sex
Male    22.284500  19.791237
Female  17.977879  18.105185

In [ ]:
df.pivot_table(index='sex',columns='smoker',values='total_bill',aggfunc='min')

/tmp/ipython-input-1572470464.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex',columns='smoker',values='total_bill',aggfunc='min')

smoker   Yes    No
sex
Male    7.25  7.51
Female  3.07  7.25

In [ ]:
df.pivot_table(index=['sex','smoker'],columns=['day','time'],values='total_bill')

/tmp/ipython-input-4109034156.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index=['sex','smoker'],columns=['day','time'],values='total_bill')

day                 Thur               Fri                Sat        Sun
time               Lunch Dinner      Lunch  Dinner     Dinner     Dinner
sex    smoker
Male   Yes     19.171000    NaN  11.386667  25.892  21.837778  26.141333
       No      18.486500    NaN        NaN  17.475  19.929063  20.403256
Female Yes     19.218571    NaN  13.260000  12.200  20.266667  16.540000
       No      15.899167  18.78  15.980000  22.750  19.003846  20.824286