# Import library

In [1]:
import pandas as pd
import numpy as np

# Load the data

In [7]:
from google.colab import files
upload = files.upload()

Saving car_dataset.csv to car_dataset.csv

# Looking the data

In [8]:
df = pd.read_csv('car_dataset.csv')

In [12]:
df = df.iloc[:, : -1]

In [13]:
df

         brand  km_drive      fule           owner  selling price
0        Honda     88374  Electric           First        1016667
1     Mercedes     49957  Electric          Second        2276914
2          BMW    131909    Hybrid  Fourth & Above         882917
3          BMW    186561    Diesel          Second        2666660
4    Chevrolet     89865  Electric  Fourth & Above        1272075
..         ...       ...       ...             ...            ...
195      Honda    111579    Petrol  Fourth & Above        2156004
196    Hyundai    195517    Hybrid          Second        2343558
197    Hyundai     90732    Petrol          Second        1606265
198       Ford    159165    Petrol           Third         182479
199   Mercedes    132500    Diesel          Second        1046593

[200 rows x 5 columns]

In [14]:
df['brand'].value_counts()

brand
Chevrolet     27
Ford          25
Toyota        22
Honda         21
Hyundai       20
Nissan        20
BMW           19
Volkswagen    18
Mercedes      16
Kia           12
Name: count, dtype: int64

In [15]:
df['brand'].nunique()

10

# OHE using PANDAS

In [17]:
pd.get_dummies(df,columns=['fule','owner'])

,brand,km_drive,selling price,fule_Diesel,fule_Electric,fule_Hybrid,fule_Petrol,owner_First,owner_Fourth & Above,owner_Second,owner_Third
0,Honda,88374,1016667,False,True,False,False,True,False,False,False
1,Mercedes,49957,2276914,False,True,False,False,False,False,True,False
2,BMW,131909,882917,False,False,True,False,False,True,False,False
3,BMW,186561,2666660,True,False,False,False,False,False,True,False
4,Chevrolet,89865,1272075,False,True,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...
195,Honda,111579,2156004,False,False,False,True,False,True,False,False
196,Hyundai,195517,2343558,False,False,True,False,False,False,True,False
197,Hyundai,90732,1606265,False,False,False,True,False,False,True,False
198,Ford,159165,182479,False,False,False,True,False,False,False,True
199,Mercedes,132500,1046593,True,False,False,False,False,False,True,False

# K -1 ONE ( remove 1st col for OHE)

In [18]:
pd.get_dummies(df,columns=['fule','owner'] , drop_first=True)

,brand,km_drive,selling price,fule_Electric,fule_Hybrid,fule_Petrol,owner_Fourth & Above,owner_Second,owner_Third
0,Honda,88374,1016667,True,False,False,False,False,False
1,Mercedes,49957,2276914,True,False,False,False,True,False
2,BMW,131909,882917,False,True,False,True,False,False
3,BMW,186561,2666660,False,False,False,False,True,False
4,Chevrolet,89865,1272075,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...
195,Honda,111579,2156004,False,False,True,True,False,False
196,Hyundai,195517,2343558,False,True,False,False,True,False
197,Hyundai,90732,1606265,False,False,True,False,True,False
198,Ford,159165,182479,False,False,True,False,False,True
199,Mercedes,132500,1046593,False,False,False,False,True,False

# ONE USING Sklearn

In [19]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(df.iloc[:,0:4] , df.iloc[:,-1],test_size = 0.2 , random_state=42)

In [20]:
from sklearn.preprocessing import OneHotEncoder

# OHE With top categories

In [21]:
df.head()

       brand  km_drive      fule           owner  selling price
0      Honda     88374  Electric           First        1016667
1   Mercedes     49957  Electric          Second        2276914
2        BMW    131909    Hybrid  Fourth & Above         882917
3        BMW    186561    Diesel          Second        2666660
4  Chevrolet     89865  Electric  Fourth & Above        1272075

In [22]:
counts = df['brand'].value_counts()

In [23]:
counts

brand
Chevrolet     27
Ford          25
Toyota        22
Honda         21
Hyundai       20
Nissan        20
BMW           19
Volkswagen    18
Mercedes      16
Kia           12
Name: count, dtype: int64

In [24]:
ohe = OneHotEncoder()

In [27]:
X_train_new = ohe.fit_transform(X_train[['fule','owner']]).toarray()

In [28]:
X_test_new = ohe.transform(X_test[['fule','owner']]).toarray()

In [31]:
X_train[['brand','km_drive']].values

array([['Mercedes', 169854],
       ['Hyundai', 90732],
       ['Ford', 91648],
       ['Hyundai', 33426],
       ['Toyota', 122151],
       ['Honda', 111579],
       ['Hyundai', 42369],
       ['Hyundai', 172863],
       ['Kia', 70414],
       ['Honda', 161812],
       ['Mercedes', 122474],
       ['Nissan', 35060],
       ['Ford', 194670],
       ['Honda', 184482],
       ['Ford', 127710],
       ['Honda', 165419],
       ['Chevrolet', 191875],
       ['Honda', 25043],
       ['Nissan', 20220],
       ['Toyota', 60152],
       ['Toyota', 29701],
       ['Toyota', 93179],
       ['Nissan', 167095],
       ['Kia', 115152],
       ['Mercedes', 23431],
       ['Honda', 38513],
       ['Mercedes', 85483],
       ['Nissan', 173557],
       ['Ford', 163025],
       ['Ford', 156126],
       ['Honda', 27319],
       ['BMW', 164301],
       ['Hyundai', 105756],
       ['Chevrolet', 197880],
       ['Volkswagen', 40518],
       ['Honda', 34148],
       ['Chevrolet', 191083],
       ['Honda', 89878],
       ['Honda', 106053],
       ['Chevrolet', 128896],
       ['BMW', 131909],
       ['Nissan', 83922],
       ['Volkswagen', 86304],
       ['Mercedes', 196181],
       ['Mercedes', 112325],
       ['Volkswagen', 54694],
       ['Mercedes', 41866],
       ['BMW', 104629],
       ['Hyundai', 73512],
       ['Volkswagen', 9087],
       ['Hyundai', 6236],
       ['Volkswagen', 34961],
       ['Volkswagen', 129251],
       ['Volkswagen', 192384],
       ['Chevrolet', 154116],
       ['Hyundai', 41369],
       ['Chevrolet', 183089],
       ['Ford', 27260],
       ['BMW', 58638],
       ['Hyundai', 127299],
       ['Chevrolet', 89865],
       ['Honda', 167819],
       ['Ford', 78417],
       ['Ford', 136807],
       ['Nissan', 83847],
       ['Toyota', 102329],
       ['Kia', 9334],
       ['Ford', 72236],
       ['BMW', 174897],
       ['Chevrolet', 104076],
       ['Chevrolet', 29724],
       ['Honda', 88374],
       ['Ford', 159165],
       ['BMW', 86670],
       ['Volkswagen', 27203],
       ['Honda', 135959],
       ['BMW', 45273],
       ['Toyota', 182773],
       ['Honda', 107726],
       ['Chevrolet', 135646],
       ['Hyundai', 25810],
       ['Nissan', 148774],
       ['Hyundai', 44456],
       ['Kia', 154439],
       ['Chevrolet', 29605],
       ['BMW', 174412],
       ['BMW', 81317],
       ['Toyota', 143289],
       ['Mercedes', 17302],
       ['BMW', 187191],
       ['Nissan', 98759],
       ['Chevrolet', 113504],
       ['Toyota', 101551],
       ['Hyundai', 130637],
       ['BMW', 7288],
       ['Mercedes', 74329],
       ['BMW', 186561],
       ['Chevrolet', 60357],
       ['Hyundai', 104545],
       ['Ford', 24991],
       ['Nissan', 70393],
       ['Kia', 179877],
       ['Honda', 85657],
       ['Ford', 170045],
       ['Volkswagen', 98509],
       ['Toyota', 109231],
       ['Toyota', 111999],
       ['Toyota', 77506],
       ['Nissan', 51017],
       ['Ford', 152131],
       ['BMW', 108924],
       ['Volkswagen', 183286],
       ['Chevrolet', 193973],
       ['Nissan', 40785],
       ['Kia', 78879],
       ['Toyota', 65649],
       ['Chevrolet', 38373],
       ['Toyota', 153672],
       ['Volkswagen', 10143],
       ['Chevrolet', 134943],
       ['Hyundai', 89560],
       ['Kia', 191137],
       ['BMW', 146641],
       ['Honda', 176413],
       ['Volkswagen', 98963],
       ['Ford', 28067],
       ['Honda', 156541],
       ['Chevrolet', 81524],
       ['Hyundai', 195517],
       ['Nissan', 134993],
       ['Hyundai', 100790],
       ['Mercedes', 142899],
       ['Ford', 105368],
       ['Ford', 146624],
       ['Ford', 81420],
       ['Toyota', 184406],
       ['Chevrolet', 17054],
       ['Nissan', 110476],
       ['Honda', 187276],
       ['Kia', 60585],
       ['Mercedes', 49957],
       ['Ford', 137628],
       ['Volkswagen', 100726],
       ['Ford', 21569],
       ['Chevrolet', 85097],
       ['Toyota', 154853],
       ['BMW', 29082],
       ['Volkswagen', 84731],
       ['Toyota', 167469],
       ['Volkswagen', 188859],
       ['Nissan', 179834],
       ['Mercedes', 132500],
       ['Chevrolet', 31089],
       ['Toyota', 111233],
       ['Nissan', 197379],
       ['Ford', 100584],
       ['Hyundai', 195839],
       ['Mercedes', 177928],
       ['Mercedes', 198010],
       ['Toyota', 71011]], dtype=object)

In [32]:
np.hstack((X_train[['brand','km_drive']].values,X_train_new)).shape

(160, 10)

# OHE with top Categories

In [35]:
df['brand'].value_counts()

brand
Chevrolet     27
Ford          25
Toyota        22
Honda         21
Hyundai       20
Nissan        20
BMW           19
Volkswagen    18
Mercedes      16
Kia           12
Name: count, dtype: int64

In [39]:
rep = counts[counts <= 20].index

In [40]:
rep

Index(['Hyundai', 'Nissan', 'BMW', 'Volkswagen', 'Mercedes', 'Kia'], dtype='object', name='brand')

In [42]:
pd.get_dummies(df['brand'].replace(rep,'uncommon')).sample(5)

     Chevrolet   Ford  Honda  Toyota  uncommon
91       False  False  False   False      True
9         True  False  False   False     False
178      False  False  False   False      True
198      False   True  False   False     False
162      False  False  False   False      True